# The Docker image that will be used to build your app
image: alpine:latest

pages:
    stage: deploy
    script: 
    - echo 'Nothing to do..'
    artifacts:
        paths:
        - public
        expire_in: 1 day
    only:
    - main
